[package]
name = "client_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = "0.13.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"

client_bridge = { path = "../client_bridge" }